# Generated by Django 4.1.3 on 2022-12-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "name",
                    models.CharField(db_collation="utf8mb4_general_ci", max_length=50),
                ),
                (
                    "id",
                    models.CharField(
                        db_collation="utf8mb4_general_ci",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pw1",
                    models.CharField(db_collation="utf8mb4_general_ci", max_length=50),
                ),
                (
                    "pw2",
                    models.CharField(db_collation="utf8mb4_general_ci", max_length=50),
                ),
                (
                    "email",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=50),
                ),
                ("regdate", models.DateField()),
            ],
            options={"db_table": "members", "managed": False,},
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("number", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("writer", models.CharField(max_length=50)),
                ("regdate", models.DateField()),
                ("views", models.IntegerField()),
                ("content", models.TextField()),
            ],
            options={"db_table": "notice", "managed": False,},
        ),
    ]
