# Generated by Django 4.1.4 on 2022-12-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_cafelist_mylike_mybookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybookmark',
            options={'managed': False},
        ),
    ]
