# Generated by Django 4.1.4 on 2022-12-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_mybookmark_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mybookmark',
            table='mybookmark',
        ),
    ]
